### ISSUE TITLE
compile error on Ubuntu 15.10

### ISSUE THREAD

**Issue by legluondunet** [dankan1890/mewui#12]
Hello,

I have a compile error on Ubuntu 15.10:

http://pastebin.com/NeBE9EM0

Thank you for your help.

LGDN

**Comment by dankan1890** [comment]
It seems to be missing part of the library qt5, try to install the following packages "qtbase5-dev" "qt5-default" "qttools5-dev-tools".

**Comment by legluondunet** [comment]
I installed qt5-default, make clean and it compiles OK now.
It's a new dependency for Mewui?

**Comment by dankan1890** [comment]
I think it is a new dependency of MAME on Linux, but having no way to do testing.
