### ISSUE TITLE
Unexpected configuration file activity

### ISSUE THREAD

**Issue by h0tw1r3** [dankan1890/mewui#13]
Mewui is storing state information such as last_used_filter and last_used_machine, therefor it does not honor the `writeconfig` config option.

Possible ways to honor writeconfig:
1. store all mewui options in a separate ini file
2. add option in the misc menu to enable/disable writeconfig.
3. show a warning when changing emu_options and writeconfig is disabled.

**Comment by dankan1890** [comment]
I know about this, the only possible way is to save the settings in a separate file.
I put it in my TODO list :)

**Comment by dankan1890** [comment]
Upon investigation I found that the option in question is fully honored by the MEWUI.
The option writeconfig (or -wc) is used to create a file of options specific to each machine started ("romset" .ini), and has nothing to do with the mame.ini.
In fact, if the program is started without specifying any machine in command line (or just double click), there is an option that is "impaired" as behavior, resulting as always active, and it's the createconfig.
This behavior is the same that the MameUI (and drivate), and I see no reason to change it.

However, I'm open to any further suggestions :)

**Comment by h0tw1r3** [comment]
Thanks for clarifying.

> In fact, if the program is started without specifying any machine in command line (or just double click), there is an option that is "impaired" as behavior, resulting as always active, and it's the createconfig.

Yes, I noticed that it always creates a configuration file, which is unexpected. Particularly on *nix where the default location is not the cwd like windows.
While I would consider that a bug that should be fixed, it is not what I am referring to.

Configuration changes are saved unexpectedly to the mame.ini file.
Example (I'm using linux): Working directory: `~/mewui`
1. `./mewui64 -createconfig`
2. Copy configuration `mame.ini` to `vector.ini`
3. Edit `vector.ini`, change contrast and gamma.
4. `./mewui64` and start Star Wars (or any vector game).
5. Quit game and mewui.

For some reason, there is a ~/.mame/mame.ini file with vector.ini values and the mewui state info (last_used_*) updated.

```
--- /home/h0tw1r3/.mame/mame.ini    2016-01-14 12:56:27.592084489 -0600
+++ mame.ini    2016-01-14 12:54:04.344934700 -0600
@@ -32,8 +32,8 @@
 skip_biosmenu             0
 skip_partsmenu            0
 start_filter              0
-last_used_filter          All
-last_used_machine         topgunnr
+last_used_filter          
+last_used_machine         

 #
 # MEWUI UI OPTIONS
@@ -141,8 +141,8 @@
 # CORE SCREEN OPTIONS
 #
 brightness                1.0
-contrast                  2.0
-gamma                     2.0
+contrast                  1.0
+gamma                     1.0
 pause_brightness          0.65
 effect                    none

@@ -150,8 +150,8 @@
 # CORE VECTOR OPTIONS
 #
 antialias                 1
-beam_width_min            2.0
-beam_width_max            2.0
+beam_width_min            1.0
+beam_width_max            1.0
 beam_intensity_weight     0
 flicker                   0
```

**Comment by dankan1890** [comment]
The issue is not "closely" related to the MEWUI, but it is probably a wrong options file management of MAME.
For example:
1. Execute `mametiny64 -cc`
2. Copy `mame.ini` in `vector.ini`
3) Change the gamma from `1.0` to `2.0` in `vector.ini`
4) Start `mametiny64 topgunnr`
5) In the sliders menu, the item gamma is `2.0` (right for a vector game)
6) From the menu, select a new machine (`wrally`) and start it
7) In the sliders menu, the item gamma is always `2.0` (not `1.0` as it should be)

The issue is not hard to fix, but I have to properly evaluate any side effects before applying it :)
