### ISSUE TITLE
Zip files cannot be extracted with standard extraction utilities

### ISSUE THREAD

**Issue by balr0g** [dankan1890/mewui#16]
The built-in Windows, Mac, and Info-Zip unzip programs are unable to extract the archive. WinZip also has this issue.
The errors output by the Info-Zip unzip program on Mac are as follows:

`skipping <filename>    need PK compat. v6.3 (can do v2.1)`

How are the archives zipped?

**Comment by dankan1890** [comment]
The files are compressed with 7zip LZMA Ultra mode.
Thanks for the feedback, I'll try to find a compromise (size / compatibility) for the next release.

**Comment by balr0g** [comment]
@dankan1890 if you want to use LZMA Ultra, I suggest just packing the files as 7zip. With regular zip, it's important that anyone can unpack them with a standard ZIP unpacker.

http://superuser.com/a/742034 suggests that the following settings will produce the best standards-compliant ZIP files:
`7za a -mm=Deflate -mfb=258 -mpass=15`
