### ISSUE TITLE
Bitmapped gfx aren't scaled in UI elements

### ISSUE THREAD

**Issue by ppriest** [dankan1890/mewui#17]
The bitmapped elements in the UI aren't scaled.

At low resolutions (e.g. 320x240, typical 15kHz arcade cab res) they're huge, and at 2160x1440 (e.g.a modern hdpi screen) they're tiny. 
This includes the mouse cursor.

See https://imgur.com/u72Ucji (320x240) / https://imgur.com/eWtFbDc (2160x1440 hdpi)

**Comment by ppriest** [comment]
Also, the smaller (than default) font for the left list and top-left corner isn't legible at the smallest resolutions.

**Comment by dankan1890** [comment]
I've made a first attempt to fix this situation, let me know if it work.

**Comment by ppriest** [comment]
Cool, looks good with a quick test.
