### ISSUE TITLE
No mouse pointer

### ISSUE THREAD

**Issue by NULUSIOS** [dankan1890/mewui#19]
Using embedded MEWUI in latest MAME 0.171 (and also same thing for HBMAME 0.171) I don't seem my mouse pointer in the GUI. Pointer _IS_ there (because if I move mouse, it highlights things) but is invisible.

System: Dual screen Windows 10 x64 (latest patches and nVidia graphics drivers).

**Comment by dankan1890** [comment]
The "Show mouse pointer" option is enabled?

**Comment by NULUSIOS** [comment]
Indeed ui_mouse was 0 (which is the default and I think a bad default).

But I have a new issue that fits in the same topic. With pointer enabled (in mame.ini), if I go to a game and quit it, there is no pointer again.
