### ISSUE TITLE
Crash pulling up menu when disk is loaded on favorited machine

### ISSUE THREAD

**Issue by ghost** [dankan1890/mewui#2]
Tested with c64p and apple2ee

When a disk is loaded on a favorited machine in MEWUI, pulling up the system menu (cheats, file manager, about, etc.) crashes MEWUI with the following message:

---

Exception at EIP=000000000264B080 (not found): ACCESS VIOLATION
## While attempting to read memory at 0000000000000018

RAX=0000000000000001 RBX=000000000AA5E3A0 RCX=0000000015EEE460 RDX=0000000000000000
RSI=0000000000000004 RDI=0000000013E94D80 RBP=0000000000000000 RSP=00000000002492C0
 R8=000000000AA5E658  R9=0000000000000006 R10=0000000000000006 R11=0000000000000006
## R12=0000000000000000 R13=0000000000249870 R14=0000000000000001 R15=0000000000000000

Stack crawl:
  0000000000249330: 000000000264B080 (not found)
  00000000002493C0: 0000000002667496 (not found)
  0000000000249400: 0000000002605AF9 (not found)
  0000000000249490: 00000000025CB508 (not found)
  0000000000249500: 0000000002636BB5 (not found)
  0000000000249550: 0000000002531C2B (not found)
  00000000002495C0: 0000000002531ED5 (not found)
  0000000000249660: 000000000255209A (not found)
  00000000002496C0: 0000000002560858 (not found)
  000000000024F6B0: 0000000002553EAF (not found)
  000000000024F850: 00000000025F9071 (not found)
  000000000024FE00: 0000000001589E05 (not found)
  000000000024FE50: 00000000029E6DEE (not found)
  000000000024FF20: 00000000004013CA (not found)
  000000000024FF50: 00000000004014F8 (not found)
  000000000024FF80: 00007FFF500B2D92 (BaseThreadInitThunk+0x0022)
  000000000024FFD0: 00007FFF50289F64 (RtlUserThreadStart+0x0034)

Happens on both targets.

**Comment by dankan1890** [comment]
Unfortunately i'm not able to reproduce this issue.
Please give me more info, system specs, MEWUI version and a step by step to reproduce the issue. 

Thanks.

**Comment by ghost** [comment]
Repro steps for C64p:
1. launch c64p with any d64 image in 1541 drive 1
2. press scroll lock and tab to open MAME menu
3. crash

MEWUI latest git, x64 compiled build (also present in MEWUI 0.163 32-bit)

OS: Microsoft Windows 10 Pro Build 10240 *\* CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (3.00 GHz) *\* RAM: 16325 MB Total (11624 MB Free) *\* VGA: NVIDIA GeForce GTX 750 Ti

**Comment by dankan1890** [comment]
I tried several floppy disks, but no crash occurs.
There may be some compatibility problems, you should try it into a new folder.
These are my screenshot:
![mweui64_1](https://cloud.githubusercontent.com/assets/7107228/8765754/32d9f86e-2e1d-11e5-8d26-be2c7802a689.png)
![mewui64_2](https://cloud.githubusercontent.com/assets/7107228/8765755/3bc9bf90-2e1d-11e5-9d64-767fd76827f3.png)

**Comment by ghost** [comment]
> There may be some compatibility problems, you should try it into a new folder.

I have put the software in different folders, and same crash everytime. If you can't reproduce the bug, I guess this is unsolvable by any means.

**Comment by ghost** [comment]
howeever, I think it might be CPU specific. my i7 CPU is third-gen. Also, try loading a d64 not from the software list and see if that makes MEWUI crash then if you open the menu again.

**Comment by dankan1890** [comment]
I confirm that I have made many tests but MEWUI still does not crash.
As a final test, before having to close the report as unreproducible, I am attaching a version only with MESS systems and compiled with the level of symbols 2.
Unpack it in a new folder, do a "mewui64--cc mess" and configure only the folders "roms" and "hash".

Hopefully in the crash log now there are more helpful information.

https://mega.co.nz/#!bo0ymQIT!sL7K-DngQci0RtbSWcNc1VOoCkUff63-T_t-20Nrs8s

**Comment by mixxmaster** [comment]
Weird, your version of MEWUI doesn't produce this bug for me. I think the regression might be after .163 r30.

**Comment by mixxmaster** [comment]
dankan1980: Seems to be an issue of the MAME/MESS merge, MESS-only binaries I compile do not produce this bug.

**Comment by ghost** [comment]
dankan1890: I HAVE FOUND REAL CAUSE OF THE BUG.

It only crashes if you follow the steps on a favorited machine.

**Comment by ghost** [comment]
---

Exception at EIP=00000000028ED46C (software_info::shortname() const+0x000c): ACCESS VIOLATION

## While attempting to read memory at 0000000000000018

RAX=0000000000000000 RBX=000000001250D830 RCX=0000000000000000 RDX=0000000000000080
RSI=0000000000000000 RDI=00000000003C98D0 RBP=0000000000249150 RSP=0000000000249150
 R8=0000000006345428  R9=0000000000000006 R10=0000000000000006 R11=0000000000000006

## R12=0000000000000008 R13=0000000000000022 R14=0000000000000000 R15=0000000000000000

Stack crawl:
  0000000000249150: 00000000028ED46C (software_info::shortname() const+0x000c)
  00000000002491E0: 0000000001DD5F54 (favorite_manager::isgame_favorite()+0x00ec)
  0000000000249310: 0000000001DFF056 (ui_menu_main::populate()+0x0a96)
  0000000000249340: 0000000001DACCDB (ui_menu::do_handle()+0x003b)
  0000000000249380: 0000000001DACD83 (ui_menu::ui_handler(running_machine&, render_container_, unsigned int)+0x008d)
  0000000000249430: 0000000001D7995B (ui_manager::update_and_render(render_container_)+0x018f)
  00000000002494A0: 0000000001DC7661 (video_manager::frame_update(bool)+0x0131)
  0000000000249530: 0000000001CF9E3E (screen_device::vblank_begin()+0x00ee)
  0000000000249570: 0000000001CF8E7F (screen_device::device_timer(emu_timer&, unsigned int, int, void_)+0x003d)
  00000000002495B0: 00000000028915B1 (device_t::timer_expired(emu_timer&, unsigned int, int, void_)+0x0041)
  0000000000249600: 0000000002697D09 (device_scheduler::execute_timers()+0x00f9)
  0000000000249690: 0000000001D126AE (device_scheduler::timeslice()+0x0408)
  0000000000249720: 0000000001D19AC2 (running_machine::run(bool)+0x0208)
  000000000024F6A0: 0000000001D108CC (machine_manager::execute()+0x01e6)
  000000000024F8C0: 0000000001D88D0A (cli_frontend::execute(int, char**)+0x08da)
  000000000024FDF0: 0000000001092CF2 (utf8_main(int, char**)+0x01e6)
  000000000024FE50: 0000000002100829 (wmain+0x00b9)
  000000000024FF20: 00000000004013CA (__tmainCRTStartup+0x024a)
  000000000024FF50: 00000000004014F8 (mainCRTStartup+0x0018)
  000000000024FF80: 00007FFABCE82D92 (BaseThreadInitThunk+0x0022)
  000000000024FFD0: 00007FFABD459F64 (RtlUserThreadStart+0x0034)

**Comment by dankan1890** [comment]
Thanks!
I'll try to look and fix it as soon as possible.

**Comment by ghost** [comment]
fixed as of commit (Favorites fix part1. nw)

**Comment by dankan1890** [comment]
Good!
mixxmaster: thanks for reporting and the time spent in the various tests! :)
