### ISSUE TITLE
Remember menu focus and UI navigation feature request

### ISSUE THREAD

**Issue by neosquid** [dankan1890/mewui#3]
1. Ability for mewui to remember last system used on restart and be focused on the available games list.
2. User is able to move between the side panel menu tree containing available, unavailable, samples etc and the games list with left and right controls. 

This makes it easier if don't want to touch the mouse if you are navigating the menus with a controller only.

**Comment by dankan1890** [comment]
Hi neosquid,
about the first request, I'll try to add it in the coming hours (before the release of version 1.6).

As for the second request, is already possible to navigate the filter list with the keys and / or joystick, holding the button 1 player 1 (for the keyboard, the left CTRL) and by scrolling up and down (for keyboard, the up / down arrow keys).

I don't have a controller and I cannot test if it works, you should confirm if it works :)

**Comment by neosquid** [comment]
Hi,

Thanks for the implementing 1. remembering the last system and game on restart - works perfectly! It's very convenient now if you are using a controller.

Number 2, I couldn't find an entry in 'general inputs' to remap my left alt key to my controller button. I have to press left alt and move the joystick up and down to navigate the filter list (not left ctrl). Any ideas where to find this?

One other possible bug I noticed is that mame.ini is not saved if you move the mewui folder to C:program files. 

It only seems to work in the C:program files folder if you run the program with administrator permissions.

I had to move mewui outside of the program folder for the mame.ini to be saved with no user permission prompts.

**Comment by dankan1890** [comment]
The left ALT key doesn't need to be mapped, it should be recognized as the second button of the controller ... but in the code of version 1.66 there is a mistake and this will undermines the functioning (I hope to I have fixed it in the current source, button 1 = left CTRL and button 2 = left ALT).

I created a test version, there are only a few machines, if you want to try you can download it from -> http://mewui.altervista.org/?upload/Windows (only to use in a separate folder from the official version, if no crashes instantly).

MEWUI (or MAME) isn't designed to work properly in the system folders, best to keep it outside :)

**Comment by neosquid** [comment]
Ok, tested it - seems to work fine!

One small usability request - is it possible to have 'Favorites' Filter appear above 'Category' Filter? 
When navigating the filter menu, if you want to pass Category to Favorites it opens up a menu which you have to scroll through to quit or a hit a different button to escape the category menu. 

Would it also be possible to have an option in miscellaneous options to hide the right side panel which contains the snapshots, titles, etc?  I loved the simplicity of the original native MAME default menu list.

Thanks!

**Comment by dankan1890** [comment]
> Ok, tested it - seems to work fine!

Thanks for testing, good to know it works :)

> One small usability request - is it possible to have 'Favorites' Filter appear above 'Category' Filter? 
> When navigating the filter menu, if you want to pass Category to Favorites it opens up a menu which  you have to scroll through to quit or a hit a different button to escape the category menu.

I'm studying a way to work around this, simply move the items is not enough.

> Would it also be possible to have an option in miscellaneous options to hide the right side panel which contains the snapshots, titles, etc? I loved the simplicity of the original native MAME default menu list.

Personally I don't love the simplicity of MAME, this is why I created the project MEWUI :)
Anyway, I'm working on the code in order to "close" the left / right panels, useful by using MEWUI on Android.

**Comment by dankan1890** [comment]
Small update.

The function to hide the side panels has been implemented, the option is not under "Miscellaneous" but under "Customize UI".
Click directly on the arrows at the side, leads to the same effect, the setting is saved when you exit (or start a machine).

You can download the trial version by the same link -> http://mewui.altervista.org :)

Regarding the other issue, at this time I have no solutions, I hope to find something before the next release.

For the moment I close this ticket, for any issues on the new features (or other requests), please open another one (so I avoid having to scroll through the thread to see new answers ... I admit, I'm lazy :P ).

**Comment by neosquid** [comment]
Ok, and thanks - will try it out!
