### ISSUE TITLE
Bad link to SDL library in OSX

### ISSUE THREAD

**Issue by Klezstyle** [dankan1890/mewui#5]
The mewui port for Mac OSX does not work because it tries to load SDL from a linux like location.

Just launch it from the command line and it reveals what is wrong:

dyld: Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
Reason image not found
Trace/BPT trap: 5

This does not work in osx, because directory /usr/local does not exist (this is a linux typical structure)

In osx the SDL library is installed (globally) in:
/Library/Frameworks/SDL2.framework (this is a folder)

The main binary library is:
/Library/Frameworks/SDL2.framework/Versions/Current/SDL2 (this is a 1,7mb binary file)

If you need me to test something just drop me a mail
klez (a) klezstyle [dot] com

**Comment by Klezstyle** [comment]
The mewui port for Mac OSX does not work because it tries to load SDL from a linux like location.

Just launch it from the command line and it reveals what is wrong:

dyld: Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
Reason image not found
Trace/BPT trap: 5

This does not work in osx, because directory /usr/local does not exist (this is a linux typical structure)

In osx the SDL library is installed (globally) in:
/Library/Frameworks/SDL2.framework (this is a folder)

The main binary library is:
/Library/Frameworks/SDL2.framework/Versions/Current/SDL2 (this is a 1,7mb binary file)

If you need me to test something just drop me a mail
klez (a) klezstyle [dot] com

**Comment by dankan1890** [comment]
Hi Klez,
unfortunately I don't use a MAC OSX and I can't give you a big help ... but you've already tried:

```
brew update
brew install sdl2 sdl2_ttf
```

?

**Comment by Klezstyle** [comment]
End users using Osx only need to install the SDL2 in binary form, like a single DLL in windows.
The library that your program should look for is this:
"/Library/Frameworks/SDL2.framework/Versions/Current/SDL2"

Development headers could be a different thing, but for launching compiled binaries the only thing you need is the SDL binary installed in the above path.

So, summarizing all.

Mewui for osx does not launch because it can´t load SDL2, because is expecting to find it in the wrong path (linux like /usr/local/lib) instead of /Library/Frameworks. Your binary must load SDL from the path explained above, like sdlmame does.

I looks like a somewhat straightforward patch but i´m not familiar with the compilation. 

Maybe this person could bring some light - "Jay" http://www.lngn.net/  https://twitter.com/sdlmame_osx/  - He publishes binary builds of sdlmame for osx on a regular basis. I wrote him a few times in the past and he seems to be a nice guy, maybe he can spot the bug in mewui (some 'ifdef' in makefiles maybe?). I even asked if he could compile mewui for osx, but it told me that he coudn´t because compilation errors.

Well, see you and write me if you find something new. You are very close to get mewui multiplatform :)
- Klez

**Comment by dankan1890** [comment]
Try this http://mewui.altervista.org/upload/Mac/mewui64-mac-sdlframework.zip and let me know if it works :)

**Comment by Klezstyle** [comment]
F I X E D !

That new build works perfectly. This issue can be closed. Thank you very much :)

It wasn't that hard, no?
- Klez

**Comment by dankan1890** [comment]
With the next release, there will be two versions for Mac, one with SDL "unix-style" and the other with the use of the framework.

Thanks for reporting and tips :)
