### ISSUE TITLE
A UI option to toggle rom information in brackets data from the list of game names

### ISSUE THREAD

**Issue by neosquid** [dankan1890/mewui#6]
e.g Capcom Sports Club (EURO 971017) becomes Capcom Sports Club

This could make the game list look more pleasant to read.

Thanks for considering this!

**Comment by dankan1890** [comment]
Remove the information in the brackets, in many cases, would lead to confusion between the various roms sets and would make it difficult to distinguish between them.

I'm sorry, but for this reason, I will not add this option.
