### ISSUE TITLE
19th October Test Build - game detection errors still present

### ISSUE THREAD

**Issue by neosquid** [dankan1890/mewui#9]
Still have the issue: did the following narrower test with less rom zips to compare the release and oct 19th test build

I'm currently running Windows 10 64 Bit Pro Version

Tested:

mewui test version (64bit) unzipped to desktop
mewui 0.166 (32bit) release unzipped to desktop

I added the following same 4 roms to each roms folder within the above mewui version folders on my desktop:

xevious.zip , xexes.zip, xmcota.zip , xmen.zip

mewui 0.166 release detects all 4 of the above roms in my arcade/available list plus breakout, pong,breakout

mewui test version only detects xmcota.zip in my arcade/available list. Auditing has no effect.

**Comment by dankan1890** [comment]
It's right.
The test version contains only a few machine, and those that you used, only xmcota is available.
If you search with the filter "All" activated, you can see that the others aren't listed :)

**Comment by neosquid** [comment]
I patiently await the new release, and think twice before reporting bugs on test versions!

**Comment by dankan1890** [comment]
Reports of possible issues with the test build is **essential**, maybe I avoid having to release a correction immediately after (as happened, 1.65 and 1.65a), and is made available for this reason.
